"ap" (* slogan = "Auto Provisioning supports the automated roll out of nodes" *) WS "resume" (* slogan = "Resume integration of a node" *) RESUME_OPTION

RESUME_OPTION ::= WS "-n" (* slogan = "Specify the node to integrate" *) WS <node_name> (* slogan = "Scope the Command using a Node name. E.g. MyNode1" *)