"ap" (* slogan = "Auto Provisioning supports the automated roll out of nodes" *) WS "skip" (* slogan = "Skip importing the current failed artifact for a node" *) SKIP_OPTION

SKIP_OPTION ::= WS "-n" (* slogan = "Specify the node to skip" *) WS <node_name> (* slogan = "Scope the Command using a Node name. E.g. MyNode1" *)
