#%RAML 1.0 DataType

name: Profile1
graphic:
  name: profile1.png
  content: ddjkjdkjdjd
ciq:
  name: input.csv
  content: gfgfgfgfg
properties: "{prop1:someprop}"
configurations:
  -
    name: profile.zip
    content: =gfgfgfgfg
status:
  isValid: true
  details: []
version:
  productNumber: R23542
  productRelease: R35535
ossModelIdentity: SOME_IDENTITY
upgradePackageName: UPGRADE_PACKAGE
getConfigScript:
  name: profile1.xml
  content: hghgghghghghg
