#%RAML 1.0 DataType

name: Profile1
version:
  productNumber: R3527
  productRelease: R387397
ossModelIdentity: SOME_IDENTITY
upgradePackageName: UPGRADE_PACKAGE
properties: "{prop1:someprop}"
graphicLocation: /some/graphic/file/location
graphic:
  name: profile1.png
  content: ddjkjdkjdjd
profileContentLocation: /some/profile/content/file/location
configurations:
  -
    name: profile.zip
    content: =gfgfgfgfg
ciq:
  ciqLocation: /some/ciq/file/location
status:
  isValid: true
  details: [details1,details2]
filterLocation: /some/getConfigScript/file/location
getConfigScript:
  name: profile1.xml
  content:  hghgghghghghg
